BEGIN;

CREATE OR REPLACE TABLE {TARGET_TABLE} AS

SELECT DATA:production_date::DATE AS PRODUCTION_DATE,
       DATA:creative_id::varchar AS CREATIVE_ID,
       SERVER_TIME::timestamp_ntz AS _TST,
       CURRENT_TIMESTAMP AS INSERT_TIME
FROM {SOURCE_TABLE}
;

COMMIT;
