BEGIN;


DELETE
FROM {TARGET_TABLE}
WHERE {SLICE}
;

INSERT INTO {TARGET_TABLE}
SELECT DATE,
       APP,
       ADOPS.PLATFORM,
       ADOPS.COUNTRYCODE,
       0 AS ACTIVEUSERS,
       0 AS ENGAGEDUSERS,
       REVENUE,
       GAME_ID,
       COUNTRY_ID,
       DATE_ID
FROM
    (SELECT DATE,
           APP,
           PLATFORM,
           COUNTRYCODE,
           SUM(REVENUE) REVENUE,
           REGEXP_REPLACE(DATE,'\\-|\\-|\\-','')  DATE_ID
    FROM L1_ADOPS.IRONSOURCE_ADOPS
    GROUP BY DATE, APP, PLATFORM, COUNTRYCODE) ADOPS
LEFT JOIN KG_DWH.L1_REFERENCE_DATA.DIM_COUNTRY DIM_COUNTRY
ON ADOPS.COUNTRYCODE = DIM_COUNTRY.COUNTRY_CODE

LEFT JOIN KG_DWH.L1_REFERENCE_DATA.DIM_GAME DIM_GAME
ON ADOPS.APP = DIM_GAME.BUNDLE_IDENTIFIER
   AND ADOPS.PLATFORM = DIM_GAME.PLATFORM
WHERE {SLICE}
;


COMMIT;
