name: "data_engineering_project"
version: "1.0.0"

profile: dp_project

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"


config-version: 2

models:
    dp_project:
        materialized: table
