BEGIN;

TRUNCATE KG_DWH.L1_BUSINESS_CONFIDENTIAL.NEUTRALREVENUE;

INSERT INTO KG_DWH.L1_BUSINESS_CONFIDENTIAL.NEUTRALREVENUE

SELECT DATA:Contact::VARCHAR CONTACT,
       DATA: Date::DATE DATE,
       DATA:Category::VARCHAR CATEGORY,
       DATA:Period::DATE PERIOD,
       DATA:Subcategory::VARCHAR SUBCATEGORY,
       DATA:Dollar_Cost::NUMBER NET_AMOUNT,
       CURRENT_TIMESTAMP()
FROM KG_DWH.RAW_BUSINESS_CONFIDENTIAL.NEUTRALREVENUE
;

COMMIT;