BEGIN;

CREATE OR REPLACE TABLE L2_BUSINESS_MODEL.APPSFLYER_ACTIVE_USERS AS

SELECT TO_DATE(INSTALL_TIME)::DATE                                                     INSTALL_DATE,
       MEDIA_SOURCE::VARCHAR                                                           MEDIA_SOURCE,
       COUNTRY_CODE::VARCHAR                                                           COUNTRY_CODE,
       CAMPAIGN_ID::VARCHAR                                                            CAMPAIGN_ID,
       SUB_CAMPAIGN_ID::VARCHAR                                                        SUB_CAMPAIGN_ID,
       COUNT(DISTINCT IFF(DAYS_SINCE_INSTALL = 0, APPSFLYER_DEVICE_ID, NULL))::NUMBER  INSTALL_DAY_USERS,
       COUNT(DISTINCT IFF(DAYS_SINCE_INSTALL = 1, APPSFLYER_DEVICE_ID, NULL))::NUMBER D01_ACTIVE_USERS,
       COUNT(DISTINCT IFF(DAYS_SINCE_INSTALL = 3, APPSFLYER_DEVICE_ID, NULL))::NUMBER  D03_ACTIVE_USERS,
       COUNT(DISTINCT IFF(DAYS_SINCE_INSTALL = 7, APPSFLYER_DEVICE_ID, NULL))::NUMBER  D07_ACTIVE_USERS,
       COUNT(DISTINCT IFF(DAYS_SINCE_INSTALL = 14, APPSFLYER_DEVICE_ID, NULL))::NUMBER D14_ACTIVE_USERS,
       COUNT(DISTINCT IFF(DAYS_SINCE_INSTALL = 30, APPSFLYER_DEVICE_ID, NULL))::NUMBER D30_ACTIVE_USERS,
       COUNT(DISTINCT IFF(DAYS_SINCE_INSTALL = 60, APPSFLYER_DEVICE_ID, NULL))::NUMBER D60_ACTIVE_USERS,
       COUNT(DISTINCT IFF(DAYS_SINCE_INSTALL = 90, APPSFLYER_DEVICE_ID, NULL))::NUMBER D90_ACTIVE_USERS,
       CURRENT_TIMESTAMP::TIMESTAMP_NTZ                                                INSERT_TIME,
       INSTALL_DATE::TIMESTAMP_NTZ                                                     _TST

FROM L1_APPSFLYER_DATALOCKER_EVENT.APPSFLYER_DATALOCKER_SESSIONS
GROUP BY INSTALL_DATE, MEDIA_SOURCE, CAMPAIGN_ID, COUNTRY_CODE, SUB_CAMPAIGN_ID
;
COMMIT;
