CREATE TABLE IF NOT EXISTS KG_DWH.L2_MARKETING_USER_LEVEL_MODEL.USER_COAL_SHAFT_5_COUNT
(
    INSTALL_TIME               TIMESTAMP_NTZ,
    APPSFLYER_DEVICE_ID        VARCHAR,
    TO_DATE_COAL_SHAFT_5_COUNT NUMBER,
    D01_COAL_SHAFT_5_COUNT     NUMBER,
    D02_COAL_SHAFT_5_COUNT     NUMBER,
    D03_COAL_SHAFT_5_COUNT     NUMBER,
    D04_COAL_SHAFT_5_COUNT     NUMBER,
    D05_COAL_SHAFT_5_COUNT     NUMBER,
    D06_COAL_SHAFT_5_COUNT     NUMBER,
    D07_COAL_SHAFT_5_COUNT     NUMBER,
    D14_COAL_SHAFT_5_COUNT     NUMBER,
    D30_COAL_SHAFT_5_COUNT     NUMBER,
    D60_COAL_SHAFT_5_COUNT     NUMBER,
    D90_COAL_SHAFT_5_COUNT     NUMBER,
    INSERT_TIME                                TIMESTAMP_NTZ,
    _TST                                       TIMESTAMP_NTZ

);

BEGIN;

TRUNCATE TABLE KG_DWH.L2_MARKETING_USER_LEVEL_MODEL.USER_COAL_SHAFT_5_COUNT;

INSERT INTO KG_DWH.L2_MARKETING_USER_LEVEL_MODEL.USER_COAL_SHAFT_5_COUNT

SELECT INSTALL_TIME,
       APPSFLYER_DEVICE_ID,
       LEAST(COUNT(APPSFLYER_DEVICE_ID), 1)                                     TO_DATE_COAL_SHAFT_5_COUNT,
       LEAST(COUNT(IFF(DAYS_SINCE_INSTALL < 1, APPSFLYER_DEVICE_ID, NULL)), 1)  D01_COAL_SHAFT_5_COUNT,
       LEAST(COUNT(IFF(DAYS_SINCE_INSTALL < 2, APPSFLYER_DEVICE_ID, NULL)), 1)  D02_COAL_SHAFT_5_COUNT,
       LEAST(COUNT(IFF(DAYS_SINCE_INSTALL < 3, APPSFLYER_DEVICE_ID, NULL)), 1)  D03_COAL_SHAFT_5_COUNT,
       LEAST(COUNT(IFF(DAYS_SINCE_INSTALL < 4, APPSFLYER_DEVICE_ID, NULL)), 1)  D04_COAL_SHAFT_5_COUNT,
       LEAST(COUNT(IFF(DAYS_SINCE_INSTALL < 5, APPSFLYER_DEVICE_ID, NULL)), 1)  D05_COAL_SHAFT_5_COUNT,
       LEAST(COUNT(IFF(DAYS_SINCE_INSTALL < 6, APPSFLYER_DEVICE_ID, NULL)), 1)  D06_COAL_SHAFT_5_COUNT,
       LEAST(COUNT(IFF(DAYS_SINCE_INSTALL < 7, APPSFLYER_DEVICE_ID, NULL)), 1)  D07_COAL_SHAFT_5_COUNT,
       LEAST(COUNT(IFF(DAYS_SINCE_INSTALL < 14, APPSFLYER_DEVICE_ID, NULL)), 1) D14_COAL_SHAFT_5_COUNT,
       LEAST(COUNT(IFF(DAYS_SINCE_INSTALL < 30, APPSFLYER_DEVICE_ID, NULL)), 1) D30_COAL_SHAFT_5_COUNT,
       LEAST(COUNT(IFF(DAYS_SINCE_INSTALL < 60, APPSFLYER_DEVICE_ID, NULL)), 1) D60_COAL_SHAFT_5_COUNT,
       LEAST(COUNT(IFF(DAYS_SINCE_INSTALL < 90, APPSFLYER_DEVICE_ID, NULL)), 1) D90_COAL_SHAFT_5_COUNT,
       CURRENT_TIMESTAMP::TIMESTAMP_NTZ                   INSERT_TIME,
       TO_DATE(INSTALL_TIME)::TIMESTAMP_NTZ               _TST

FROM L1_APPSFLYER_PUSH_API_EVENT.APPSFLYER_COAL_SHAFT_5 COAL_SHAFT_5
GROUP BY INSTALL_TIME, APPSFLYER_DEVICE_ID
;

COMMIT;
