
BEGIN;

TRUNCATE TABLE IF EXISTS KG_DWH.L1_GAME_BUILD_PIPELINE.BUILD_HEALTH;

CREATE OR REPLACE TABLE KG_DWH.L1_GAME_BUILD_PIPELINE.BUILD_HEALTH AS
WITH BuildHealthJson AS (
    SELECT parse_json(TO_VARIANT(DATA)):BuildHealth AS BUILD_HEALTH FROM RAW_GAME_BUILD_PIPELINE.BUILD_HEALTH
)
SELECT BUILD_HEALTH:AppVersion::STRING        AS APP_VERSION,
       BUILD_HEALTH:Artifact::STRING          AS ARTIFACT,
       BUILD_HEALTH:BundleIdentifier::STRING  AS BUNDLE_IDENTIFIER,
       BUILD_HEALTH:Configuration::STRING     AS CONFIGURATION,
       BUILD_HEALTH:Platform::STRING          AS PLATFORM,
       BUILD_HEALTH:Product::STRING           AS PRODUCT,
       TRY_TO_NUMBER(BUILD_HEALTH:SizeInKBytes::TEXT)    AS SIZE_IN_KBYTES,
       BUILD_HEALTH:TriggerTimeUTC::TIMESTAMP AS TRIGGER_TIME_UTC  
FROM BuildHealthJson;

COMMIT;