BEGIN;

CREATE OR REPLACE TABLE {TARGET_TABLE} AS


SELECT DATA:ID::VARCHAR ID,
DATA:Category::VARCHAR CATEGORY,
       DATA:Description1::VARCHAR DESCRIPTION_1,
       DATA:Description2::VARCHAR    DESCRIPTION_2,
       DATA:ItemValueEuro::VARCHAR ITEM_VALUE_EURO,
       DATA:ItemValueSC::VARCHAR ITEM_VALUE_SC,
      CURRENT_TIMESTAMP AS _TST
FROM {SOURCE_TABLE}
;


COMMIT;
