CREATE OR REPLACE TABLE KG_DWH.L2_MARKETING_COHORT_MODEL.AD_WATCHED_COUNT_REVENUE AS

WITH AD_WATCHED AS
         (SELECT TO_DATE(INSTALL_TIME) INSTALL_DATE,
                 DAYS_SINCE_INSTALL,
                 MEDIA_SOURCE,
                 CAMPAIGN_ID,
                 SUB_CAMPAIGN_ID,
                 COUNTRY_CODE,
                 EVENT_TIME,
                 GAME_NAME,
                 PLATFORM
          FROM L1_APPSFLYER_PUSH_API_EVENT.APPSFLYER_AD_WATCHED),

     ---Ad_revenue
     AD_REV AS (
         SELECT DATE         AS EVENT_DATE,
                COUNTRY_CODE AS COUNTRY_CODE,
                GAME_NAME    AS GAME_NAME,
                PLATFORM     AS PLATFORM,
                REVENUE      AS REVENUE
         FROM L2_ADOPS_MODEL.AD_REVENUE),

     --Combine Ad_rev and ad_count
     AD_REV_COUNT AS
         (SELECT AD_REV.EVENT_DATE            EVENT_DATE,
                 AD_REV.COUNTRY_CODE       AS COUNTRY_CODE,
                 AD_REV.GAME_NAME          AS GAME_NAME,
                 AD_REV.PLATFORM           AS PLATFORM,
                 AD_REV.REVENUE            AS REVENUE,
                 AD_COUNT.AD_WATCHED_COUNT AS AD_WATCHED_COUNT
          FROM AD_REV
                   LEFT OUTER JOIN (SELECT *
                                    FROM L2_MARKETING_COHORT_MODEL.AD_WATCHED_COUNT) AD_COUNT
                                   ON AD_REV.EVENT_DATE = ad_count.EVENT_DATE
                                       AND AD_REV.COUNTRY_CODE = ad_count.COUNTRY_CODE
                                       AND AD_REV.GAME_NAME = ad_count.GAME_NAME
                                       AND AD_REV.PLATFORM = ad_count.PLATFORM),
     ---select for rev_per_ecap
     REV_PER_ECAP AS (
         SELECT AD_REV_COUNT.EVENT_DATE,
                AD_REV_COUNT.COUNTRY_CODE,
                AD_REV_COUNT.GAME_NAME,
                AD_REV_COUNT.PLATFORM,
                COALESCE(SUM(REVENUE) / SUM(AD_WATCHED_COUNT), 0) AS REV_PER_ECAP
         FROM AD_REV_COUNT

         GROUP BY EVENT_DATE,
                  COUNTRY_CODE,
                  GAME_NAME,
                  PLATFORM)


---Calculate your measures
     SELECT INSTALL_DATE::DATE INSTALL_DATE,
    MEDIA_SOURCE::VARCHAR MEDIA_SOURCE,
    COUNTRY_CODE::VARCHAR COUNTRY_CODE,
    CAMPAIGN_ID::VARCHAR CAMPAIGN_ID,
    SUB_CAMPAIGN_ID::VARCHAR SUB_CAMPAIGN_ID,
    COUNT(*)::BIGINT AS AD_WATCHED_COUNT,
    COUNT(IFF(DAYS_SINCE_INSTALL < 1, 1, NULL))::BIGINT D01_AD_WATCHED_COUNT,
    COUNT(IFF(DAYS_SINCE_INSTALL < 3, 1, NULL))::BIGINT D03_AD_WATCHED_COUNT,
    COUNT(IFF(DAYS_SINCE_INSTALL < 7, 1, NULL))::BIGINT D07_AD_WATCHED_COUNT,
    COUNT(IFF(DAYS_SINCE_INSTALL < 14, 1, NULL))::BIGINT D14_AD_WATCHED_COUNT,
    COUNT(IFF(DAYS_SINCE_INSTALL < 30, 1, NULL))::BIGINT D30_AD_WATCHED_COUNT,
    COUNT(IFF(DAYS_SINCE_INSTALL < 60, 1, NULL))::BIGINT D60_AD_WATCHED_COUNT,
    COUNT(IFF(DAYS_SINCE_INSTALL < 90, 1, NULL))::BIGINT D90_AD_WATCHED_COUNT,
    COUNT(IFF(DAYS_SINCE_INSTALL < 180, 1, NULL))::BIGINT D180_AD_WATCHED_COUNT,
    COUNT(IFF(DAYS_SINCE_INSTALL < 360, 1, NULL))::BIGINT D360_AD_WATCHED_COUNT,
    COALESCE(SUM(REV_PER_ECAP), 0)::FLOAT AS AD_WATCHED_REVENUE,
    SUM(IFF(DAYS_SINCE_INSTALL < 1, REV_PER_ECAP, 0))::FLOAT D01_AD_WATCHED_REVENUE,
    SUM(IFF(DAYS_SINCE_INSTALL < 3, REV_PER_ECAP, 0))::FLOAT D03_AD_WATCHED_REVENUE,
    SUM(IFF(DAYS_SINCE_INSTALL < 7, REV_PER_ECAP, 0))::FLOAT D07_AD_WATCHED_REVENUE,
    SUM(IFF(DAYS_SINCE_INSTALL < 14, REV_PER_ECAP, 0))::FLOAT D14_AD_WATCHED_REVENUE,
    SUM(IFF(DAYS_SINCE_INSTALL < 30, REV_PER_ECAP, 0))::FLOAT D30_AD_WATCHED_REVENUE,
    SUM(IFF(DAYS_SINCE_INSTALL < 60, REV_PER_ECAP, 0))::FLOAT D60_AD_WATCHED_REVENUE,
    SUM(IFF(DAYS_SINCE_INSTALL < 90, REV_PER_ECAP, 0))::FLOAT D90_AD_WATCHED_REVENUE,
    SUM(IFF(DAYS_SINCE_INSTALL < 180, REV_PER_ECAP, 0))::FLOAT D180_AD_WATCHED_REVENUE,
    SUM(IFF(DAYS_SINCE_INSTALL < 360, REV_PER_ECAP, 0))::FLOAT D360_AD_WATCHED_REVENUE,
    CURRENT_TIMESTAMP::TIMESTAMP_NTZ INSERT_TIME,
    INSTALL_DATE::TIMESTAMP_NTZ _TST

FROM (
    ---Bring Ad_watched and REV_ECAP  together
    SELECT
    INSTALL_DATE,
    DAYS_SINCE_INSTALL,
    MEDIA_SOURCE,
    CAMPAIGN_ID,
    SUB_CAMPAIGN_ID,
    AD_WATCHED.COUNTRY_CODE COUNTRY_CODE,
    REV_PER_ECAP
    FROM AD_WATCHED
    LEFT OUTER JOIN REV_PER_ECAP
    ON REV_PER_ECAP.EVENT_DATE = TO_DATE(AD_WATCHED.EVENT_TIME)
    AND REV_PER_ECAP.COUNTRY_CODE = AD_WATCHED.COUNTRY_CODE
    AND REV_PER_ECAP.GAME_NAME = AD_WATCHED.GAME_NAME
    AND REV_PER_ECAP.PLATFORM = AD_WATCHED.PLATFORM)


GROUP BY INSTALL_DATE,
    MEDIA_SOURCE,
    CAMPAIGN_ID,
    COUNTRY_CODE,
    SUB_CAMPAIGN_ID
;

COMMIT;
