BEGIN;
CREATE OR REPLACE VIEW L2_MARKETING_COHORT_MODEL.BID_AUTOMATION AS

WITH MARKETING_COHORT_MEASURES AS (SELECT INSTALL_DATE,
                   GAME_NAME,
                   PLATFORM,
                   COUNTRY_CODE,
                   MEDIA_SOURCE,
                   CAMPAIGN_NAME,
                   CAMPAIGN_ID,
                   SUB_CAMPAIGN_NAME,
                   SUB_CAMPAIGN_ID,

                   --CUMULATIVE INSTALLS
                   SUM(INSTALL_COUNT)
                       OVER (PARTITION BY CAMPAIGN_ID, SUB_CAMPAIGN_ID, COUNTRY_CODE ORDER BY INSTALL_DATE DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE_INSTALL_COUNT,

                   --CUMULATIVE COST
                   SUM(COST)
                       OVER (PARTITION BY CAMPAIGN_ID, SUB_CAMPAIGN_ID, COUNTRY_CODE ORDER BY INSTALL_DATE DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE_COST,

                   --CUMULATIVE PRED_D90_REVENUE
                   SUM(PRED_D90_REVENUE)
                       OVER (PARTITION BY CAMPAIGN_ID, SUB_CAMPAIGN_ID, COUNTRY_CODE ORDER BY INSTALL_DATE DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE_PRED_D90_REVENUE,

                   --COUNT ROWS
                   ROW_NUMBER()
                           OVER (PARTITION BY CAMPAIGN_ID, SUB_CAMPAIGN_ID, COUNTRY_CODE ORDER BY INSTALL_DATE DESC)                                              AS CUMULATIVE_DAYS,

                   --DYNAMIC COUNTRY TIER NEEDED FOR PERFORMANCE TARGET JOIN
                   COALESCE(PERFORMANCE_TARGET_TBL.COUNTRY_TIER, 'ROW')                                                                                           AS TARGET_COUNTRY_GROUP,

                   --DYNAMIC MEDIA SOURCE NEEDED FOR BID AUTOMATION VARIABLES JOIN
                   COALESCE(BID_AUTOMATION_TBL.COUNTRY_GROUP, 'ROW')                                                                                              AS BID_COUNTRY_GROUP

            FROM L2_MARKETING_COHORT_MODEL.MARKETING_COHORT

                     LEFT OUTER JOIN (SELECT DISTINCT COUNTRY_TIER
                                      FROM L1_MARKETING.STATIC_PERFORMANCE_TARGET) PERFORMANCE_TARGET_TBL
                                     ON PERFORMANCE_TARGET_TBL.COUNTRY_TIER = COUNTRY_CODE

                     LEFT OUTER JOIN (SELECT DISTINCT COUNTRY_GROUP
                                      FROM L2_MARKETING_COHORT_MODEL.STATIC_BID_AUTOMATION_VARIABLES) BID_AUTOMATION_TBL
                                     ON BID_AUTOMATION_TBL.COUNTRY_GROUP = COUNTRY_CODE


            WHERE INSTALL_DATE > DATEADD('DAY', -90, CURRENT_DATE())),


     CUMULATIVE_COHORT AS (
         SELECT *
         FROM (
                  --CALCULATING DERIVED METRICS CPI AND PERFORMANCE
                  SELECT MARKETING_COHORT_MEASURES.*,
                         TARGET.PERFORMANCE_TARGET, --PERFORMANCE TARGET,
                         BID.MINIMUM_BID,
                         BID.MAXIMUM_BID,
                         BID.INSTALLS_SAMPLE_SIZE,
                         BID.LESS_THAN_50_PERCENT,
                         BID.PERFORMANCE_50_TO_75_PERCENT,
                         BID.PERFORMANCE_75_TO_90_PERCENT,
                         BID.PERFORMANCE_90_TO_100_PERCENT,
                         BID.PERFORMANCE_100_TO_110_PERCENT,
                         BID.PERFORMANCE_110_TO_125_PERCENT,
                         BID.PERFORMANCE_125_TO_150_PERCENT,
                         BID.PERFORMANCE_GREATER_150_PERCENT,
                         ROW_NUMBER()
                                 OVER (PARTITION BY CAMPAIGN_ID, SUB_CAMPAIGN_ID, COUNTRY_CODE ORDER BY INSTALL_DATE DESC) AS RANK

                         --SUMS UP COST AND REVENUE OF THE LAST 100 INSTALLS FOR EACH FULL BREAKDOWN IN MARKETING COHORT
                  FROM MARKETING_COHORT_MEASURES

                           --PERFORMANCE TARGET JOIN
                           LEFT JOIN L1_MARKETING.STATIC_PERFORMANCE_TARGET TARGET
                                     ON (MARKETING_COHORT_MEASURES.GAME_NAME = TARGET.GAME_NAME
                                         AND MARKETING_COHORT_MEASURES.PLATFORM = TARGET.PLATFORM
                                         AND MARKETING_COHORT_MEASURES.TARGET_COUNTRY_GROUP = TARGET.COUNTRY_TIER)

                      --BID AUTOMATION VARIABLES JOIN
                           LEFT JOIN L2_MARKETING_COHORT_MODEL.STATIC_BID_AUTOMATION_VARIABLES BID
                                     ON (MARKETING_COHORT_MEASURES.GAME_NAME = BID.GAME_NAME
                                         AND MARKETING_COHORT_MEASURES.PLATFORM = BID.PLATFORM
                                         AND MARKETING_COHORT_MEASURES.BID_COUNTRY_GROUP = BID.COUNTRY_GROUP)

--DESIRED INSTALL THRESHOLD, BASED ON THE STATIC_BID_AUTOMATION_VARIABLES TABLE
                  WHERE CUMULATIVE_INSTALL_COUNT > BID.INSTALLS_SAMPLE_SIZE
              )
-- FIRST ROW WHERE INSTALL THRESHOLD IS REACHED, DON'T CHANGE
         WHERE RANK = 1
     )

--ATTENTION THE ACTUAL SUGGESTED BID IS CALCULATED IN LOOKER BECAUSE IT DEPENDS ON THE SELECTED BREAKDOWN
SELECT *
FROM CUMULATIVE_COHORT
WHERE MEDIA_SOURCE != 'Organic'
;
COMMIT;
