CREATE TABLE IF NOT EXISTS KG_DWH.L2_MARKETING_COHORT_MODEL.CAMPAIGN_INFORMATION
(
    CAMPAIGN_ID       VARCHAR,
    SUB_CAMPAIGN_ID   VARCHAR,
    CAMPAIGN_NAME     VARCHAR,
    SUB_CAMPAIGN_NAME VARCHAR,
    GAME_NAME          VARCHAR,
    PLATFORM          VARCHAR,
    MEDIA_SOURCE      VARCHAR,
    SOURCE            VARCHAR,
    INSERT_TIME       TIMESTAMP_NTZ
);

BEGIN;

TRUNCATE TABLE KG_DWH.L2_MARKETING_COHORT_MODEL.CAMPAIGN_INFORMATION;

INSERT INTO KG_DWH.L2_MARKETING_COHORT_MODEL.CAMPAIGN_INFORMATION

--Finds the most frequent campaign name, sub campaign name, game name, platform, and source per MEDIA_SOURCE, CAMPAIGN_ID, SUB_CAMPAIGN_ID breakdown
SELECT CAMPAIGN_ID,
       SUB_CAMPAIGN_ID,
       MODE(CAMPAIGN_NAME)     as CAMPAIGN_NAME,
       MODE(SUB_CAMPAIGN_NAME) as SUB_CAMPAIGN_NAME,
       MODE(GAME_NAME)         as GAME_NAME,
       MODE(PLATFORM)          as PLATFORM,
       MEDIA_SOURCE,
       MODE(SOURCE)            as SOURCE,
       CURRENT_TIMESTAMP::TIMESTAMP_NTZ
FROM L1_APPSFLYER_PUSH_API_EVENT.APPSFLYER_INSTALL
GROUP BY MEDIA_SOURCE, CAMPAIGN_ID, SUB_CAMPAIGN_ID;


COMMIT;
