CREATE TABLE IF NOT EXISTS KG_DWH.L2_MARKETING_COHORT_MODEL.INSTALL_COUNT
(
    INSTALL_DATE    DATE,
    MEDIA_SOURCE    VARCHAR,
    COUNTRY_CODE    VARCHAR,
    CAMPAIGN_ID     VARCHAR,
    SUB_CAMPAIGN_ID VARCHAR,
    INSTALL_COUNT   BIGINT,
    TOTAL_USD_REPORTED_COST_PER_INSTALL FLOAT,
    INSERT_TIME     TIMESTAMP_NTZ,
    _TST            TIMESTAMP_NTZ
);

BEGIN;

TRUNCATE TABLE KG_DWH.L2_MARKETING_COHORT_MODEL.INSTALL_COUNT;

INSERT INTO KG_DWH.L2_MARKETING_COHORT_MODEL.INSTALL_COUNT
SELECT TO_DATE(INSTALL_TIME)              INSTALL_DATE,
       MEDIA_SOURCE,
       COUNTRY_CODE,
       CAMPAIGN_ID,
       SUB_CAMPAIGN_ID,
       COUNT(*)                           INSTALL_COUNT,
       SUM(USD_REPORTED_COST_PER_INSTALL) TOTAL_USD_REPORTED_COST_PER_INSTALL,
       CURRENT_TIMESTAMP::TIMESTAMP_NTZ   INSERT_TIME,
       INSTALL_DATE::TIMESTAMP_NTZ        _TST
FROM KG_DWH.L1_APPSFLYER_PUSH_API_EVENT.APPSFLYER_INSTALL
GROUP BY INSTALL_DATE, MEDIA_SOURCE, CAMPAIGN_ID, COUNTRY_CODE, SUB_CAMPAIGN_ID
;

COMMIT;
