BEGIN;

CREATE OR REPLACE VIEW KG_DWH.L2_MARKETING_COHORT_MODEL.MARKETING_COST AS

WITH COST_UNION AS (
    SELECT DATE,
           MEDIASOURCE,
           COUNTRYCODE,
           CAMPAIGNID,
           SUBCAMPAIGNID,
           SUM(COST) COST
    FROM (
             SELECT DATE, MEDIASOURCE, COUNTRYCODE, CAMPAIGNID, SUBCAMPAIGNID, COST
             FROM "KG_DWH"."L1_MARKETING_COST"."MARKETING_COST_APPLE_ADS"

             UNION ALL

             SELECT DATE, MEDIASOURCE, COUNTRYCODE, CAMPAIGNID, SUBCAMPAIGNID, ECPI
             FROM "KG_DWH"."L1_MARKETING_COST"."IRONSOURCE_CPE_CAMPAIGN_COST"

             UNION ALL

             SELECT DATE, MEDIASOURCE, COUNTRYCODE, CAMPAIGNID, SUBCAMPAIGNID, COST
             FROM "KG_DWH"."L1_MARKETING_COST"."MARKETING_COST_APPLOVIN"

             UNION ALL

             SELECT DATE, MEDIASOURCE, COUNTRYCODE, CAMPAIGNID, SUBCAMPAIGNID, COST
             FROM "KG_DWH"."L1_MARKETING_COST"."MARKETING_COST_BEESWAX"

             UNION ALL

             SELECT DATE, MEDIASOURCE, COUNTRYCODE, CAMPAIGNID, SUBCAMPAIGNID, COST
             FROM "KG_DWH"."L1_MARKETING_COST"."MARKETING_COST_BLAST"


             UNION ALL
             SELECT DATE, MEDIASOURCE, COUNTRYCODE, CAMPAIGNID, SUBCAMPAIGNID, COST
             FROM "KG_DWH"."L1_MARKETING_COST"."MARKETING_COST_CROSSINSTALL"

             UNION ALL
             SELECT DATE, MEDIASOURCE, COUNTRYCODE, CAMPAIGNID, SUBCAMPAIGNID, COST
             FROM "KG_DWH"."L1_MARKETING_COST"."MARKETING_COST_FACEBOOK"

             UNION ALL
             SELECT DATE, MEDIA_SOURCE, COUNTRY_CODE, CAMPAIGN_ID, SUBCAMPAIGN_ID, COST
             FROM "KG_DWH"."L1_MARKETING_COST"."MARKETING_COST_GOOGLE"

             UNION ALL
             SELECT DATE, MEDIA_SOURCE, COUNTRY_CODE, CAMPAIGN_ID, SUBCAMPAIGN_ID, COST
             FROM "KG_DWH"."L1_MARKETING_COST"."MARKETING_COST_IRONSRC_CPE"

             UNION ALL
             SELECT DATE, MEDIASOURCE, COUNTRYCODE, CAMPAIGNID, SUBCAMPAIGNID, COST
             FROM "KG_DWH"."L1_MARKETING_COST"."MARKETING_COST_KAYZEN"

             UNION ALL
             SELECT DATE, MEDIA_SOURCE, COUNTRY_CODE, CAMPAIGN_ID, SUB_CAMPAIGN_ID, COST
             FROM "KG_DWH"."L1_MARKETING_COST"."MARKETING_COST_LIFTOFF"

             UNION ALL
             SELECT DATE, MEDIASOURCE, COUNTRYCODE, CAMPAIGNID, SUBCAMPAIGNID, COST
             FROM "KG_DWH"."L1_MARKETING_COST"."MARKETING_COST_MOBVISTA"

             UNION ALL
             SELECT DATE, MEDIASOURCE, COUNTRYCODE, CAMPAIGNID, SUBCAMPAIGNID, COST
             FROM "KG_DWH"."L1_MARKETING_COST"."MARKETING_COST_SNAPCHAT"

             UNION ALL
             SELECT DATE, MEDIASOURCE, COUNTRYCODE, CAMPAIGNID, SUBCAMPAIGNID, COST
             FROM "KG_DWH"."L1_MARKETING_COST"."MARKETING_COST_TAPJOY"

             UNION ALL
             SELECT DATE, MEDIASOURCE, COUNTRYCODE, CAMPAIGNID, SUBCAMPAIGNID, COST
             FROM "KG_DWH"."L1_MARKETING_COST"."MARKETING_COST_TIKTOK"

             UNION ALL
             SELECT DATE, MEDIASOURCE, COUNTRYCODE, CAMPAIGNID, SUBCAMPAIGNID, COST
             FROM "KG_DWH"."L1_MARKETING_COST"."MARKETING_COST_TRESENSA"

             UNION ALL
             SELECT DATE, MEDIA_SOURCE, COUNTRY_CODE, CAMPAIGN_ID, SUB_CAMPAIGN_ID, COST
             FROM "KG_DWH"."L1_MARKETING_COST"."MARKETING_COST_TWITTER"

             UNION ALL
             SELECT DATE, MEDIA_SOURCE, COUNTRY_CODE, CAMPAIGN_ID, SUB_CAMPAIGN_ID, COST
             FROM KG_DWH.L1_MARKETING_COST.MARKETING_COST_TABOOLA

             UNION ALL
             SELECT DATE, MEDIA_SOURCE, COUNTRY_CODE, CAMPAIGN_ID, SUB_CAMPAIGN_ID, COST
             FROM KG_DWH.L1_MARKETING_COST.MARKETING_COST_ZUCKS
         )
    GROUP BY DATE, MEDIASOURCE, COUNTRYCODE, CAMPAIGNID, SUBCAMPAIGNID
)

SELECT DATE,
       COALESCE(MEDIASOURCE, 'None')          MEDIA_SOURCE,
       COALESCE(COUNTRY.COUNTRY_CODE, 'None') COUNTRY_CODE,
       COALESCE(CAMPAIGNID, 'None')           CAMPAIGN_ID,
       COALESCE(SUBCAMPAIGNID, 'None')        SUB_CAMPAIGN_ID,
       COST
FROM COST_UNION
         LEFT JOIN L1_REFERENCE_DATA.DIM_COUNTRY COUNTRY
                   ON COUNTRY.COUNTRY_CODE = COST_UNION.COUNTRYCODE
;

COMMIT;
