CREATE TABLE IF NOT EXISTS KG_DWH.L2_MARKETING_COHORT_MODEL.PURCHASE_UNIQUE_USERS
(
    INSTALL_DATE    DATE,
    MEDIA_SOURCE    VARCHAR,
    COUNTRY_CODE    VARCHAR,
    CAMPAIGN_ID     VARCHAR,
    SUB_CAMPAIGN_ID VARCHAR,
    TO_DATE_UNIQUE_PURCHASERS BIGINT,
    INSERT_TIME     TIMESTAMP_NTZ,
    _TST            TIMESTAMP_NTZ
);

BEGIN;

TRUNCATE TABLE KG_DWH.L2_MARKETING_COHORT_MODEL.PURCHASE_UNIQUE_USERS;

INSERT INTO KG_DWH.L2_MARKETING_COHORT_MODEL.PURCHASE_UNIQUE_USERS


SELECT TO_DATE(INSTALL_TIME) INSTALL_DATE,
       MEDIA_SOURCE,
       COUNTRY_CODE,
       CAMPAIGN_ID,
       SUB_CAMPAIGN_ID,
       COUNT(DISTINCT APPSFLYER_DEVICE_ID)              TO_DATE_UNIQUE_PURCHASERS,
       CURRENT_TIMESTAMP::TIMESTAMP_NTZ   INSERT_TIME,
       INSTALL_DATE::TIMESTAMP_NTZ        _TST


FROM L1_APPSFLYER_PUSH_API_EVENT.APPSFLYER_IN_APP_PURCHASE
GROUP BY INSTALL_DATE, MEDIA_SOURCE, CAMPAIGN_ID, COUNTRY_CODE, SUB_CAMPAIGN_ID
;
COMMIT;

