CREATE TABLE IF NOT EXISTS L2_BLACKLIST_PLAYERS.CLIENTSDK_QA_DEVICE_LIST (
  DEVICE_ID VARCHAR,
  INSERT_TIME TIMESTAMP_NTZ,
  _TST TIMESTAMP_NTZ
);

BEGIN;

INSERT INTO L2_BLACKLIST_PLAYERS.CLIENTSDK_QA_DEVICE_LIST
SELECT
      DISTINCT DATA:DeviceId :: STRING DEVICE_ID,
      CURRENT_TIMESTAMP INSERT_TIME,
      CURRENT_DATE _TST
FROM RAW_CLIENTSDK_EVENT.CLIENTSDK_EVENT_QA
WHERE SERVER_TIME >= DATEADD( 'DAYS', -3, CURRENT_TIMESTAMP)
  AND DEVICE_ID NOT IN (SELECT DEVICE_ID FROM L2_BLACKLIST_PLAYERS.CLIENTSDK_QA_DEVICE_LIST);

COMMIT;
