BEGIN;

CREATE OR REPLACE TABLE {TARGET_TABLE} AS


SELECT DATA:Offer_Name::VARCHAR OFFER_NAME,
  DATA:Offer_Type::VARCHAR OFFER_TYPE,
  DATA:Store_ID::VARCHAR STORE_ID,
  CURRENT_TIMESTAMP AS _TST
FROM {SOURCE_TABLE}
;


COMMIT;
