CREATE TABLE IF NOT EXISTS TEST_MODEL_2 AS (
    SELECT COUNTRY,
           COUNT(*) AS TOTAL_NO_CUSTOMERS,
           SUM(AMOUNT) AS TOTAL_SALES
    FROM COUNTRY
    INNER JOIN CITY ON COUNTRY.COUNTRY_ID = CITY.COUNTRY_ID
    INNER JOIN ADDRESS ON CITY.CITY_ID =ADDRESS.CITY_ID
    INNER JOIN CUSTOMER ON ADDRESS.ADDRESS_ID = CUSTOMER.ADDRESS_ID
    INNER JOIN PAYMENT ON CUSTOMER.CUSTOMER_ID = PAYMENT.CUSTOMER_ID
    GROUP BY 1
    ORDER BY 2 DESC
);