CREATE TABLE IF NOT EXISTS KG_DWH.DATA_QUALITY_METRIC.L1_APPSFLYER_GAME_KPI_HOURLY
(
    EVENT_DATE       DATE,
    HOUR             INTEGER,
    GAME_NAME        VARCHAR,
    INSTALL_COUNT    BIGINT,
    PURCHASE_REVENUE BIGINT,
    AD_WATCHED       BIGINT
)
;

BEGIN;

TRUNCATE TABLE KG_DWH.DATA_QUALITY_METRIC.L1_APPSFLYER_GAME_KPI_HOURLY
;

INSERT INTO KG_DWH.DATA_QUALITY_METRIC.L1_APPSFLYER_GAME_KPI_HOURLY

SELECT INSTALL.*, PURCHASE.PURCHASE_REVENUE, AD.AD_WATCHED
FROM (SELECT TO_DATE(EVENT_TIME) EVENT_DATE, HOUR(EVENT_TIME) HOUR, GAME_NAME, COUNT(*) INSTALL_COUNT
      FROM KG_DWH.L1_APPSFLYER_PUSH_API_EVENT.APPSFLYER_INSTALL
      GROUP BY EVENT_DATE, HOUR, GAME_NAME) INSTALL

         LEFT JOIN (SELECT TO_DATE(EVENT_TIME)               EVENT_DATE,
                           HOUR(EVENT_TIME)                  HOUR,
                           GAME_NAME,
                           SUM(REVENUE_IN_SELECTED_CURRENCY) PURCHASE_REVENUE
                    FROM KG_DWH.L1_APPSFLYER_PUSH_API_EVENT.APPSFLYER_IN_APP_PURCHASE
                    GROUP BY EVENT_DATE, HOUR, GAME_NAME) PURCHASE
                     ON INSTALL.EVENT_DATE = PURCHASE.EVENT_DATE
                       AND INSTALL.HOUR = PURCHASE.HOUR
                       AND INSTALL.GAME_NAME = PURCHASE.GAME_NAME

         LEFT JOIN (SELECT TO_DATE(EVENT_TIME) EVENT_DATE, HOUR(EVENT_TIME) HOUR, GAME_NAME, COUNT(*) AD_WATCHED
                    FROM KG_DWH.L1_APPSFLYER_PUSH_API_EVENT.APPSFLYER_AD_WATCHED
                    GROUP BY EVENT_DATE, HOUR, GAME_NAME) AD
                   ON INSTALL.EVENT_DATE = AD.EVENT_DATE
                       AND INSTALL.HOUR = AD.HOUR
                       AND INSTALL.GAME_NAME = AD.GAME_NAME
WHERE INSTALL.EVENT_DATE >= DATEADD(DAY, -21, CURRENT_DATE)
ORDER BY EVENT_DATE DESC
;

COMMIT;
