BEGIN;

CREATE TABLE IF NOT EXISTS {TARGET_TABLE}
(
    DATE DATE,
  	DATE_ID NUMBER,
  	COUNTRY_ID NUMBER,
  	GAME_ID NUMBER,
  	DAILY_ACTIVE_USERS NUMBER,
  	REVENUE DOUBLE,
  	DAILY_ENGAGED_USERS NUMBER,
    _TST  TIMESTAMPNTZ,
    INSERT_TIME TIMESTAMPNTZ
);

DELETE
FROM {TARGET_TABLE}
WHERE {SLICE}
;

INSERT INTO {TARGET_TABLE}
WITH RAW AS (
    SELECT DATA: date::DATE              DATE,
           REPLACE(DATA: date, '-')      DATE_ID,
           DIM_COUNTRY.COUNTRY_ID,
           DIM_GAME.GAME_ID,
           0                             DAILY_ACTIVE_USERS,
           DATA:estimated_revenue::FLOAT REVENUE,
           0                             DAILY_ENGAGED_USERS,
           _TST,
           CURRENT_TIMESTAMP             INSERT_TIME
    FROM {SOURCE_TABLE} REV_RAW
             LEFT JOIN L1_REFERENCE_DATA.DIM_COUNTRY DIM_COUNTRY
ON UPPER(REV_RAW.DATA:country) = DIM_COUNTRY.COUNTRY_CODE
    LEFT JOIN L1_REFERENCE_DATA.DIM_GAME DIM_GAME ON REV_RAW.DATA:package_name = DIM_GAME.BUNDLE_IDENTIFIER
    AND REV_RAW.DATA:platform = LOWER(DIM_GAME.PLATFORM)
    )
SELECT DATE,
       DATE_ID,
       COUNTRY_ID,
       GAME_ID,
       SUM(DAILY_ACTIVE_USERS)  DAILY_ACTIVE_USERS,
       SUM(REVENUE)             REVENUE,
       SUM(DAILY_ENGAGED_USERS) DAILY_ACTIVE_USERS,
       _TST,
       INSERT_TIME
FROM RAW
WHERE {SLICE}
GROUP BY DATE,
    DATE_ID,
    COUNTRY_ID,
    GAME_ID,
    _TST,
    INSERT_TIME;

COMMIT;
