BEGIN;

CREATE TABLE IF NOT EXISTS {TARGET_TABLE}
(
    DATE            DATE,
    MEDIA_SOURCE    VARCHAR,
    COUNTRY_CODE    VARCHAR,
    CAMPAIGN_ID     VARCHAR,
    SUB_CAMPAIGN_ID VARCHAR,
    COST            FLOAT,
    _TST            TIMESTAMPNTZ,
    INSERT_TIME     TIMESTAMPNTZ
);



DELETE
FROM {TARGET_TABLE}
WHERE {SLICE}
;


INSERT INTO {TARGET_TABLE}
SELECT DATA:Date::DATE DATE,
       DATA:mediasource::VARCHAR MEDIA_SOURCE,
       DATA:country::VARCHAR COUNTRY_CODE,
       DATA:campaignid::VARCHAR    CAMPAIGN_ID,
       DATA:subcampaignid::VARCHAR SUB_CAMPAIGN_ID,
       DATA:cost::FLOAT            COST,
       _TST,
      CURRENT_TIMESTAMP
FROM {SOURCE_TABLE}
WHERE {SLICE}
;


COMMIT;