BEGIN;

DELETE
FROM {TARGET_TABLE}
WHERE {SLICE}
;


INSERT INTO {TARGET_TABLE}
SELECT DATA:InstallTime::DATE DATE,
       'Dataseat' AS MEDIA_SOURCE,
       DATA:AppID::VARCHAR  APPID,
       CASE
        WHEN DATA:GEO::VARCHAR = 'UK' THEN 'GB'
        ELSE DATA:GEO::VARCHAR
       END AS COUNTRYCODE,
       DATA:CampaignID::VARCHAR    CAMPAIGNID,
       DATA:PublisherIDaf_siteid::VARCHAR SUBCAMPAIGNID,
       DATA:Cost::FLOAT            COST,
       _TST,
       INSERT_TIME
FROM {SOURCE_TABLE}
WHERE {SLICE}
AND DATA:MediaSource = 'dataseat_int'
;


COMMIT;
