CREATE TABLE IF NOT EXISTS {TARGET_TABLE} AS (
  DATE DATE,
  MEDIA_SOURCE VARCHAR,
  COUNTRY_CODE VARCHAR,
  CAMPAIGN_ID VARCHAR,
  SUB_CAMPAIGN_ID VARCHAR,
  COST FLOAT,
  _TST TIMESTAMP_NTZ,
  INSERT_TIME TIMESTAMP_NTZ
)


BEGIN;

DELETE
FROM {TARGET_TABLE}
WHERE {SLICE}
;


INSERT INTO {TARGET_TABLE}
SELECT DATA:DATE::DATE DATE,
       DATA:MEDIA_SOURCE::VARCHAR    MEDIA_SOURCE,
       DATA:COUNTRY_CODE::VARCHAR    COUNTRY_CODE,
       DATA:CAMPAIGN_ID::VARCHAR     CAMPAIGN_ID,
       DATA:SUB_CAMPAIGN_ID::VARCHAR SUB_CAMPAIGN_ID,
       DATA:COST::FLOAT              COST,
       _TST,
       CURRENT_TIMESTAMP::TIMESTAMP_NTZ INSERT_TIME
FROM {SOURCE_TABLE}
WHERE {SLICE}
;


COMMIT;
