BEGIN;

DELETE
FROM {TARGET_TABLE}
WHERE {SLICE}
;


INSERT INTO {TARGET_TABLE}
SELECT EVENT:date::DATE DATE,
       EVENT:mediasource::VARCHAR  MEDIASOURCE,
       EVENT:app::VARCHAR           APP,
       EVENT:countrycode::VARCHAR   COUNTRYCODE,
       EVENT:campaignid::VARCHAR    CAMPAIGNID,
       EVENT:subcampaignid::VARCHAR SUBCAMPAIGNID,
       EVENT:cost::FLOAT            COST,
       _TST,
       INSERT_TIME
FROM {SOURCE_TABLE}
WHERE {SLICE}
;


COMMIT;
