BEGIN;

DELETE
FROM {TARGET_TABLE}
WHERE {SLICE}
;


INSERT INTO {TARGET_TABLE}
SELECT DATA:date::DATE DATE,
       'Taboola' AS  MEDIA_SOURCE,
       DATA:country::VARCHAR COUNTRY_CODE,
       DATA:campaignid::VARCHAR    CAMPAIGN_ID,
       DATA:campaignid::VARCHAR SUB_CAMPAIGN_ID,
       DATA:spent::FLOAT            COST,
       _TST,
      CURRENT_TIMESTAMP
FROM {SOURCE_TABLE}
WHERE {SLICE}
;


COMMIT;
