BEGIN;

DELETE
FROM {TARGET_TABLE}
WHERE {SLICE}
;


INSERT INTO {TARGET_TABLE}
SELECT DATA:DATE::DATE DATE,
       DATA:MEDIA_SOURCE::VARCHAR AS  MEDIA_SOURCE,
       DATA:COUNTRY_CODE::VARCHAR COUNTRY_CODE,
       DATA:CAMPAIGN_ID::VARCHAR    CAMPAIGN_ID,
       DATA:SUB_CAMPAIGN_ID::VARCHAR SUB_CAMPAIGN_ID,
       DATA:COST::FLOAT            COST,
       _TST,
      CURRENT_TIMESTAMP
FROM {SOURCE_TABLE}
WHERE {SLICE}
;


COMMIT;

;
